name: release

on:
  push:
    tags:
      - '*'

jobs:

  docker:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get branch name
        uses: nelonoel/branch-name@v1.0.1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: docker build and push
        run: |
          docker build -t 4pdosc/openaios:${BRANCH_NAME} \
            --build-arg VERSION=${BRANCH_NAME} \
            -f ./dockerfile/Dockerfile .
          docker push localhost:5000/openaios:${BRANCH_NAME}
          docker tag localhost:5000/openaios:${BRANCH_NAME} localhost:5000/openaios:latest
          docker push localhost:5000/openaios:latest
